### ISSUE TITLE
Megatinycore board installation error

### ISSUE THREAD

**Issue by nlCortana** [SpenceKonde/megaTinyCore#1022]
Today tried installing megatinycore to a fresh arduino 1.8.13 installation.

But there seems to be an error in the .json

The megaTinyCore plugin is then omitted.

```
Geleverd index bestand C:\Users\marti\AppData\Local\Arduino15\package_drazzy.com_index.json word overgeslagen, lees fout opgetreden:
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
at [Source: (FileInputStream); line: 3888, column: 14]
at [Source: (FileInputStream); line: 3887, column: 22] (through reference chain: cc.arduino.contributions.packages.ContributionsIndex["packages"]->java.util.ArrayList[1]->cc.arduino.contributions.packages.ContributedPackage["tools"]->java.util.ArrayList[11]->cc.arduino.contributions.packages.ContributedTool["systems"]->java.util.ArrayList[0])
```

**Comment by BroekerFrank** [comment]
I got the same error message.
It seams, that the JSON-file is not correct formatted.
best regards
Frank

**Comment by SpenceKonde** [comment]
Fixed

Where the hell arduino managed to dig up the worlds most pedantic json parser i'll never know. When I was looking at these for work, customers complained because our parser actually expected json, initially. It was quickly learned that this was not a reasonable expectation. Indeed, nobody else's parsers were as pedantic as ours, when we compared them; it would have totally passed that file though... Who the hell requires no comma after the last element of a list? Not even C demands that.
