### ISSUE TITLE
Menu with optimization level

### ISSUE THREAD

**Issue by michpro** [SpenceKonde/megaTinyCore#1038]
It would be nice if it was possible to set the optimization level from the menu (-Os, -O0..03, -Og, -flto).

**Comment by SpenceKonde** [comment]
This was tried and removed after discovering that nothing compiled without -Os if the sketch used serial inany way, because it doesn't like the trick I used to reduce thhe overhead for serial on some parts by over 80% (in terms of flash), and I do a similar ting with pin interupts. Greatly reduces duplicated code, but O2/O3 duiplicatedmy assembly and causes label collsions
