### ISSUE TITLE
Problem with editing boards.txt

### ISSUE THREAD

**Issue by avandalen** [SpenceKonde/megaTinyCore#1075]
Previously, this setting was always visible:
UPDI/Reset pin = Reset (DANGER)
Now you need to modify boards.txt for this.
Can you eliminate the need to edit boards.txt? The fact is that the lack of a HV UPDI programmer is actually not a problem. Burning the bootloader goes smoothly and you can check the proper functioning of UPDI in advance as mentioned in my article:
https://avdweb.nl/arduino/attiny3217/bootloader-attiny3217
Moreover, a HV programmer is very simple to make, I will publish this on my website soon....
Can you add the following in readme in case you need to change boards.txt:
1. The location of boards.txt
C:\Users\xxx\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.10
2. Describe how to edit boards.txt. It has to be done four times, on #atxy7 #atxy6 #atxy4 #atxy2

**Comment by hmeijdam** [comment]
Despite the fact that [HV unbricking](https://github.com/SpenceKonde/megaTinyCore/discussions/450) is not difficult. This option was removed on purpose, because it did more harm to people not knowing what they are doing, than benefits to people who realize what the consequences of disabling the UPDI pin are.
For the latter it will be no problem to make [some edits](https://github.com/SpenceKonde/megaTinyCore/blob/7e836cd37f56b706c6a2f5c553ef1a6e97bf8ef9/megaavr/boards.txt#L447) in boards.txt
