### ISSUE TITLE
ATtiny3216 Hardware RESET

### ISSUE THREAD

**Issue by PM04290** [SpenceKonde/megaTinyCore#1125]
As described in datasheet of ATTiny3216, it is possible to make hardware reset with low voltage, but configuration must be enabled by fuse.
On menu UDPI, i have only "No Reset" or "reset enabled for Serie 2"

How to enable hardware reset on ~Reset/UDPI pin ?

**Comment by hmeijdam** [comment]
Find the "boards.txt" file from MegatinyCore and search for the word "expert". Then you will see that you can uncomment the 'expert mode' features. Make sure you realize that you will need a HV programmer to ever set the UPDI pin back to UPDI. That is why by default these options are commented out.

![image](https://github.com/SpenceKonde/megaTinyCore/assets/9595465/3eeef554-b175-4635-a1d3-2c9b41346fd2)

**Comment by PM04290** [comment]
@hmeijdam , thanks for solution... but for HV programmer i must learn to it; actually i use simple Nano with jtag2udpi firmware... I suppose it is not an HV programmer

**Comment by hmeijdam** [comment]
No, but you can [make that into a HV programmer](https://github.com/SpenceKonde/megaTinyCore/issues/1122#issuecomment-2212326269)

**Comment by SpenceKonde** [comment]
Note that jtag2updi is deprecated, and I explicitly refuse to provide support, on the demonstrated grounds that I am incompetent to do so. Even after months of work jtag2updi chokes and breaks constantly for no apparent reason and people kept asking me questions and all I could say is "Yeah I dunno, I tried for 2 montjs to figure out what was going on, burned out so hard I had to take 2 months off modern AVRs" , Once serialUPDI was faster two, I dropped jtag2updi like a radioactive potatoe. 

My attempts at making a HV UPDI programmer have hardware ready to go but not a line of code written for them so they''re useless.

**Comment by hmeijdam** [comment]
> My attempts at making a HV UPDI programmer have hardware ready to go

Does that hardware include supporting a powercycle-HV (PC-HV) programming sequence?

**Comment by SpenceKonde** [comment]
Well, actually now that I think about it, none of them are any good anymore anyway because the absolute max on anything other than a tinyAVR that has HV UPDI is 9V, minimum needed to trigger 2V above Vdd, typ 7.5v, not min 10, typ 12 abs max 13 of modern tinyAVRs. 

Do your HV programmers account for that? 

So I had designs that I belived would work for programming, until I read that line in the updated datasheet. I don't have a good way to make 7.5V. Not a single-chip-inductor-free way like getting 12v from 5v (max662 clones are cheap and do it with afew caps. Low current, but that's no problem. I now suspect theirprogrammers that generate the HV pulse are likely using the capacitortrick like DTR reset does, only in the opposite direction, to get the pulse.

**Comment by PM04290** [comment]
I gave up on using the Reset pin, I do this directly with the power supply.

**Comment by hmeijdam** [comment]
> Do your HV programmers account for that?

No, but I would probably add a 2 or 3 leds in series, (depending on their forward voltage) to get about 7,5V from my 12V source. Then a manual button to shortcut the leds for still getting the 12V for a tinyAVR.

**Comment by SpenceKonde** [comment]
How much you wanna bet that the way Microchip does it in their programmers involves 1 diode and 2 capacitors? (and possibly no support for tinyAVR)
