### ISSUE TITLE
Feature Request:  Add support for Serial UPDI port specification separate from IDE Port: menu 

### ISSUE THREAD

**Issue by EclipseBoom** [SpenceKonde/megaTinyCore#1166]
Want to use serial UPDI programmer and still be able to debug via Serial monitor and plotter.  It looks to me like programmers.txt can specify the serial port used by the programmer independently of the IDE default serial port selection used for the Serial monitor and plotter.

Adding this feature would be much cleaner than running external serial apps or starting two copies of the IDE etc.

Perhaps this is an IDE function and not a SerialUPDI programmer subsystem function.  If so please close this issue.

**Comment by SpenceKonde** [comment]
This is an IDE issue. 
I can make tools submenus, but only with content that depends only upon the selected board, when this feature needs to be able to get the list of serial ports and propagate that menu option down to where platform.txt is getting processed (has historically been an issue at times, ie, it resolves at one point in processing but not the critical one)

In any event, the IDE's serial terminal is an unpardonable, unsalvagable piece of utter shit, literally lacking every feature I would consider essential in a serial monitor for embedded development. 
I use and recommend hTerm - I leave it open (on the data serial port) while leaving the IDE set to the upload port. Does everything conceivable and some things you haven't even imagined yet. 

I have been wiring boards up so that the nominal-CTS line is tied to UPDI - a suitable dual-serial adapter IC could then present a single 6-pin connection interface, allowing DTR reset serial and UPDI programming. I seem to have a bit of a curse w/regards to USB devices though... You don't wanna know how many revs various attempts at that have gone through.
