### ISSUE TITLE
Checking the clock speed (not an issue)

### ISSUE THREAD

**Issue by avandalen** [SpenceKonde/megaTinyCore#198]
Hi Spence 
I added this to my article: https://www.avdweb.nl/arduino/attiny3217/dily3217

Checking the clock speed
If you forget to set the clock speed with tools> Clock Speed, it can have serious consequences. For example, at the Yamaha battery dongle, to reduce power consumption, I use a clock frequency of 5MHz instead of 20MHz.  If the factory forgets to set the frequency, the dongle will still work. While the dongle still passes the test, the electronics will overheat. That is why it is important to add a test in the software. In this example, the program stops if the clock frequency is not 5Mhz.

**Comment by SpenceKonde** [comment]
That method is not complete as it does not account for what the base HF oscillator speed is set to (and is overly complicated because it checks a register, when you could simply do a compiletime check 
Using megaTinyCore, F_CPU will  always accurately identify the clock frequency of the chip as long as the OSCCFG fuse is set as expected (ie, 20MHz for 20/10/5, 16 for 16/8/4/1 As you probably know, in init(), we set the prescaler based on F_CPU (but this code does assume that the internal oscillator is set to the correct speed).  Yes, this means that the speed that the sketch was compiled with determines which clock speed it will run at - in fact the fuse only sets whether the base speed being being prescaled is 20MJz or 16MHz - so what you should really be doing is:
  
#if (F_CPU!=5000000L)
#error "Incorrect clock frequency selected"
#endif
Thus, that can be caught at COMPILETIME because the prescaler is set by the uploaded sketch, not the fuses!

Then in your runtime check, you just need to check the fuse... (this check is generic regardless of which clock speed you are using)
bool checkClockSpeed()
{ 
#if (F_CPU==20000000L || F_CPU==10000000L || F_CPU==5000000L)
  return (FUSE.OSCCFG&0x02); //see fuse description, that is the bit set to select the 20MHz oscillator speed. 
#else
return (FUSE.OSCCFG&0x01);
#endif
}

This doesn't seem to be related to the core, but rather an application code issue. Unfortunately, while the initialization function could check and determine that it was given an F_CPU not possible to achieve with the fuse (IE, fuse is not set to match sketch), there is no generic channel to propagate a runtime error.
