### ISSUE TITLE
multiple definition of nvm_write_byte error

### ISSUE THREAD

**Issue by T94T** [SpenceKonde/megaTinyCore#200]
I just tried to include your EEPROM library in a sub class. Unfortunately it gets compiled with errors listed below. Please find a very simple test project attached. With `#include <EEPROM.h>` commented out in the `Test_Class.h` file the project gets compiled without errors.

> In function 'nvm_write_byte(unsigned int, unsigned char)':
> (.text+0x0): multiple definition of 'nvm_write_byte(unsigned int, unsigned char)'
> sketch/Test.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
> collect2: error: ld returned 1 exit status

[Test.zip](https://github.com/SpenceKonde/megaTinyCore/files/4805485/Test.zip)

**Comment by SpenceKonde** [comment]
The hell? It's like the include guard isn't working... Not sure what I'm doing wrong here...

**Comment by SpenceKonde** [comment]
I looked at  this again - no idea how to fix it! 

Anyone know?

**Comment by Yardie-** [comment]
Not sure if this will help 
I found a small error in the EEPROM.h file though

line 61 
` EERef &operator=( uint8_t in )     { return nvm_write_byte( (uint8_t*) index, in ), *this;  }
` 
probably should be 

`  EERef &operator=( uint8_t in )     { return nvm_write_byte( (uint16_t) index, in ), *this;  }
`

**Comment by T94T** [comment]
The error still remains. But I found a solution/workaround.
[TestWorking.zip](https://github.com/SpenceKonde/megaTinyCore/files/4906355/TestWorking.zip)

**Comment by SpenceKonde** [comment]
It was just pointed out that there are some issues with EEPROM.h relating to workarounds (this macro, indirectly, is one of them). This is simple to sort out and will be fixed in next release. 

I may end up ripping the user row stuff out and putting it into it's own library. I think I will, that way I could have a unified API on DxCore and here for userrow programming, even though the underlying implementation has to be very different.

**Comment by T94T** [comment]
Thank you. So I'm waiting for the next release.

**Comment by SpenceKonde** [comment]
Fixed in github version will be in 2.0.6
