### ISSUE TITLE
DAC bug

### ISSUE THREAD

**Issue by iansexton** [SpenceKonde/megaTinyCore#277]
Setting   DACReference(VDD) appears to give an output range 0-0.5v whereas  DACReference(INTERNAL4V3) gives an output 0-4.3v as expected.
I appreciate that it won't do rail to rail but it shouldn't work like this?

**Comment by iansexton** [comment]
OK - I think I'm answering my own question. The data book (p.127) says, 'The default reference voltages are 0.55V' which agrees with what I found.

Your documentation (ADC Support) says:

Supported reference voltages are:

VDD (Vcc/supply voltage - default)          ///really?
INTERNAL0V55
etc etc

This doesn't add up?

You also state that the DAC has very weak drive capability and Microchip claim the exact opposite (5kohm load)

Apologies if I seem critical - what you're doing is amazing :)

**Comment by SpenceKonde** [comment]
My god, I noticed this issue, started to type explanation, and then wandered off... twice!

At power-on reset (POR), the relevant VREF registers are all set to 0x00, which happens to correspond to the 0.5V reference (since the core supports 2k parts (there is a 212) with a DAC, where you frequently *are* scrounging for every single byte of program memory you can get, we skip initialization for peripherals we don't use (who knows what the right value is anyway... it depends on the requirements of the user, and the value everyone wishes was the default isn't an option anyway)

Anyway, when DACReference() is called with VDD, since VDD is not a valid option, it can't set it to that. And it has no way to notify the program of what happened... 

The content in the `ADC Support` section (default reference, as you called out) applies to the ADC., it does not apply to the DAC unless explicitly noted. The DAC support is described just below that in the paragraph titled `DAC Support` - emphasis added. Do note that the default reference is not specified.

> ### DAC Support
> The 1-series parts have an 8-bit DAC which can generate a real analog voltage (note that this provides very low current and can only be used as a voltage reference, it cannot be used to power other devices). This generates voltages between 0 and the selected VREF **(which cannot be VDD, unfortunately)**. In 2.0.0 and later, set the DAC reference voltage via the DACReference() function - **pass it one of the INTERNAL reference options** listed under the ADC section above. In versions prior to 2.0.0, select the DAC VREF voltage from the Tools -> DAC Voltage Reference submenu. This voltage must be lower than Vcc to get the correct voltages. Call analogWrite() on the DAC pin to set the voltage to be output by the DAC. To turn off the DAC output, call digitalWrite() on that pin.

I don't argue that the behavior isn't perverse, but until very recently, I didn't know how to detect a compile-time known invalid argument and notify the user of their error.

In 2.2.0 and later, as long as the argument passed to DACReference is a compile-time known value, if it is not a valid reference option, that will be a compile error, since we know it will do nothing (in fact LTO will optimize it away entirely... pretty sure in current version if you compile with DACReference(VDD), note the size, then comment that line out and recompile, you'll find that the size is the same).

analogReference() will do the same thing, too, and the only bogus value that the digital I/O functions will take now (assuming it's compile time known - bad values generated at runtime, we can't do anything about) is -1/255/NOT_A_PIN - because some libraries rely on the user passing -1, and then merrily pass those to the builtin functions and let them decide not to do anything...  For example, SoftwareSerial expects to be able to pass -1 to pinMode.... (as an aside, that library is both a miracle and an abomination - a miracle because they made it work written in C, rather than inline assembly, and abomination because of... everything else about it)....

**Comment by SpenceKonde** [comment]
Closing because expected behavior and improvements are already in progress (though I am tightening up a way that the checking could break)

**Comment by SpenceKonde** [comment]
Regarding the matter of output drive strength - I stand by my statement `(note that this provides very low current and can only be used as a voltage reference, it cannot be used to power other devices)` - they say that it can drive a 5 kOhm resistive load and typical I<sub>out</sub> of 1mA.

**Comment by iansexton** [comment]
Cheers. We can agree to differ on high/low drive. In my book that's high :)
Powering other 'devices' is a bit vague? It'll power a transistor...
No worries - it got me off my lazy arse to RTFM :)
