### ISSUE TITLE
Documentation on LOW Power 

### ISSUE THREAD

**Issue by mrWheel** [SpenceKonde/megaTinyCore#283]
I almost dare not ask but:

Can anybody explain how I can get the power consumption in Sleep Mode (PWR_DOWN) to the minimum?

I have a bare ATtiny3216 chip with one input (switch, active LOW) and one LED (active HIGH).
The switch and UART are configured to wakeUp the chip. After a view seconds it will switch off the LED and go to sleep.

The lowest amperage I measure (CurrentRanger) is between 1 and 2mA.

![Screenshot 2020-12-21 at 13 20 17](https://user-images.githubusercontent.com/5585427/102776756-a0144780-438f-11eb-8eab-d35cc9b86c84.png)

How can I configure all pins (digital, DAC, ADC or whatever) to draw the least current?

**Comment by SpenceKonde** [comment]
This is part of #158 - I don't know how low power stuff works because I haven't really looked into it... so many features, so little time. Super looking forward to the xmas -> NY time to work on this, heh...

But "Sleep mode standby" is the one you want (check datasheet power usage section - it's basically "power down, but with option to leave things on"; you can get nearly the power usage of power-down... whilest leaving one of the 32KHz oscillators on to keep time!!!
