### ISSUE TITLE
RSP_NO_TARGET_POWER after burning bootloader

### ISSUE THREAD

**Issue by mayurharge** [SpenceKonde/megaTinyCore#537]
Hello,
I am using latest core release and these are the settings I am using while burning the bootloader, I am using burn bootloader option to do it. Core version 2.4.2
![Screenshot (56)](https://user-images.githubusercontent.com/42429307/137127522-623f9f05-3d2a-4fc1-8df5-b53d86786717.png)

After succesfully burning the bootloader and trying to upload the sketch again I get this error (I am able to successfully run my sketch before so no issue from HW design )

> avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description
avrdude: jtagmkII_program_enable(): bad response to enter progmode command: RSP_NO_TARGET_POWER
avrdude: jtagmkII_program_enable(): bad response to enter progmode command: RSP_NO_TARGET_POWER
avrdude: jtagmkII_read_byte(): bad response to read memory command: RSP_NO_TARGET_POWER
avr_read(): error reading address 0x0000
    read operation not supported for memory "signature"
avrdude: error reading signature data for part "ATtiny827", rc=-2
avrdude: error reading signature data, rc=-2
avrdude: error reading signature data for part "ATtiny827", rc=-2

My main goal is to enable external reset using UPDI or PB4 option.
Please help me to enable external reset by any means.

**Comment by SpenceKonde** [comment]
No response after nearly a week to what amounts to a tech support inquiry for a programmer we do not provide technical support for. We do not provide technical support for it because we don't know what causes it to work or not work either, sometimes it behaves oddly. We know at one point there was a busted version in my github for months because I didn't understand what I'd merged in, but that was fixed. It'sthat or a wiring problem. No UPDI perogramming will work with anything connected between the programming data line and the target's UPDI pin except a small value resistor (470 is our recommendation), and it can't have anything like an autoreset circuit connected, and the pin must not have been set to act as a reset or I/O pin,

**Comment by arihantdaga** [comment]
Also, are the fuses value set by the script is right ? Could they be problem ?
This comes when i try to upload bootloader. Set fuses: ['0:0x00', '1:0x00', '2:0x02', '4:0x00', '5:0b11001101', '6:0x04', '7:0x00', '8:0x00']. 
I am wondering if fuse 4 and 5 are right ?
I did fuse_print and the fuse values on the existing chip(Which i have uploaded my sketch into) is  `0x001284: FF, 0x001285: F6`

1. According to the docs, fuse 3 and 4 are reserved, why we are setting fuse 4 here then. 
2. Previous fuse value is F6 - i.e - 11**11**0110 and now we are setting 11**00**1101  the 4th bit is for NVM lock enable/disable, could that be a reason why the mcu would lock and appear to not respond to anything once we try to upload bootloader. 

![image](https://user-images.githubusercontent.com/4976460/138143725-89417646-987a-4cc8-a36d-5d025bb3a42c.png)

**Comment by arihantdaga** [comment]
Ohk, understood. Thank you very much. :) 
I would like to do a PR and fix this. 
Can we also enroll this repo for hacktoberfest ? 😅😅

**Comment by DominikRzecki** [comment]
> 

Hello,
I have a very similar problem with the ATtiny1624.
Did you manage to solve that, or did you just buy a new chip?

**Comment by SpenceKonde** [comment]
Just fix the bad wirining or whatever else is causing the problem. at error most often indicattes a problem with the network or device configuration
