### ISSUE TITLE
Timing problems while using ATTINY3227 with internal 1MHz

### ISSUE THREAD

**Issue by Uwne** [SpenceKonde/megaTinyCore#650]
Hi,

for a simple project I want to use the internal 1MHz clock.
After flashing the "blink without delay" code my led blinks @500ms, not @1000ms.
If I use more than 1MHz system clock it works fine.

Any idea?

edit; megaTinyCore 2.5.10 // Arduino IDE 1.8.19

BR
Uwe

**Comment by SpenceKonde** [comment]
Sounds like a bug in the core, I thought I'd fixed all of those 1 MHz-specific issues, but it sounds like not. At all other speeds when a type B timer is used for millis, the timer clock sourece is set to CLKPER / 2, and the peroiod of the millis timer (default TCB1) is set to F_CPU/2000

**Comment by SpenceKonde** [comment]
I will add that 1 MHz speed doesn't get exercised much - most people are running these things at the full 20 MHz as far as I know.

**Comment by Uwne** [comment]
Thank you very much for your quick response. Because of the power consumption I need to use the internal 1MHz.

**Comment by SpenceKonde** [comment]
The real power savings comes from spending more time in sleep modes where the clock is turned off, and it doesn't matter what speed the clock is set to. Assuming you need to do a constant number of clock cycles of work each time the chip wakes up, between which times you will be in sleep with the clock turned off, you're better off spending 1/20th as long awake at 20MHz, - Per section 33.5, active power consumption, with constant supply voltage, the power consumption increases in less than direct proportion to the clock speed (active mode 3.2 mA at 5 MHz, 5.5 mA at 10 MHz and 10.2mA at 20. Doing the same amount of work at 1 MHz will take more power than doing it much faster at 20 MHz and spending the rest of the time sleeping 

Running at lower clock speeds does matter if you need it to stay in active mode for a duration measured in units of time, rather than clock cycles of work (ex "wake up and monitor a pin for 10 seconds before returning to sleep")

**Comment by Uwne** [comment]
Yes this is exactly what I want to do. The next step is to implement sleep mode, only wake up by PCINT,
do work and go back to sleep. I also need to update a alive LED from time to time.

**Comment by SpenceKonde** [comment]
Fix for this is checked in here, porting to DxCopr as bug was also present on DxCore.
