### ISSUE TITLE
Reading RSTCTRL.RSTFR after Watchdog reset

### ISSUE THREAD

**Issue by stuartpittaway** [SpenceKonde/megaTinyCore#838]
Hi.  I'm having difficulty reading RSTCTRL.RSTFR register after power on/watchdog reset.  The flags never seem to be set.

I'm using Tiny1624 with code like this in setup().   The watchdog is set to trigger every 8 seconds, which it does, but the RSTFR bitmap isn't set.  

I would like to run different code on watchdog compared to power up.

I'm using an UPDI programmer for the chip, not using a boot loader.

Does wdt_disable clear that register?
Am I not reading the register correctly?

Many thanks for the help.

```
void setup()
{
  wdt_disable();

  // Did we have a watchdog reboot?
  if ((RSTCTRL.RSTFR & RSTCTRL_WDRF_bm) == RSTCTRL_WDRF_bm)
  {
    watchdog();
  }
}
```

**Comment by SpenceKonde** [comment]
Yes, that is exactly what it does. 
I've written extensively about why we do that - it is my firm belief that the majority of times that an Arduino (generally due to a code bug in the sketch) would get hung until manually reset is because nobody checked or cleared the reset flags, and few people knew how that could be used to - and why it was critical to - detect the case when code execution was reset without the hardware resetting.

https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/Ref_Reset.md

Whatever you're trying to do, since it involves the reset cause, you should read that document.  Modern AVRs are not classic AVRs and their reset behavior is subtly different (actually, no, that's not true, the reset differences are not at all subtle. The differences are an improvement, but one that is generally squandered because nobody handled it correctly on classic AVRs either). 

The WDT reset doesn't have the bizarre perverse behavior of classic AVRs either - after a WDT timeout, the hardware resets and the WDT is not turned back on unless the WDT fuse forces it to be.
